name: Build and Release Go Project

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    needs: build_check
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: amd64
            os: linux-latest
            name: sshs-linux-amd64

          - target: amd64
            os: darwin-latest
            name: sshs-darwin-amd64

          - target: amd64
            os: windows-latest
            name: sshs-windows-amd64

          - target: arm64
            os: linux-latest
            name: sshs-linux-arm64

          - target: arm64
            os: darwin-latest
            name: sshs-darwin-arm64

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.target }} go build -o sshs ./...
          tar czvf ${{ matrix.name }}.tar.gz sshs

      - name: Upload the build as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}.tar.gz
          path: ${{ matrix.name }}.tar.gz

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: sshs-linux-amd64.tar.gz, sshs-darwin-amd64.tar.gz, sshs-windows-amd64.tar.gz, sshs-linux-arm64.tar.gz, sshs-darwin-arm64.tar.gz

      - name: Setup | Checksums
        run: for file in *.tar.gz; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done

      - name: Release | Add Artifacts to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sshs-linux-amd64.tar.gz
            sshs-darwin-amd64.tar.gz
            sshs-windows-amd64.tar.gz
            sshs-linux-arm64.tar.gz
            sshs-darwin-arm64.tar.gz
            *.sha256
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}